# Generated by Django 4.2.28 on 2026-02-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
    ]
