# Generated by Django 4.2.28 on 2026-04-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_employee_is_verified_employee_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='otp',
        ),
    ]
